### ISSUE TITLE
Read last sms received in IOS 

### ISSUE THREAD

**Issue by nitneuq33000** [AppleEducate/plugins#1]
Hello and thank you for your job, I have see that this plugin doesn't support IOS https://pub.dartlang.org/packages/sms
Bad news ... I have done all my code thinking it was compatible...
I really need to find an alternative solution to implement my app for IOS.
Currently your package is the best alternative but do you have any plant to add listener sms? I need package able to send sms and read last sms received.

thank you

**Comment by AppleEducate** [comment]
I could possibly build something to store the last message to shared preferences but iOS does not have an API to read SMS messages on iOS (except maybe for business chat)

**Comment by AppleEducate** [comment]
I am open to pull requests if you want to do the logic in dart otherwise i will close this.
