### ISSUE TITLE
Dart Pub Analysis on flutter_whatsnew isn't too happy .. 

### ISSUE THREAD

**Issue by sjmcdowall** [AppleEducate/plugins#10]
May want to put the google (or whatever) analyze_options.yaml in place and fix the lint errors -- Dart Pub doesn't have nice things to say about the package .. (not really but..) 

https://pub.dartlang.org/packages/flutter_whatsnew#-analysis-tab-

**Comment by AppleEducate** [comment]
Please check with the latest version `0.1.0`
