### ISSUE TITLE
flutter_whatsnew : Example in Pub Dart is wrong

### ISSUE THREAD

**Issue by sjmcdowall** [AppleEducate/plugins#11]
First, it's not really an example but secondly it indicates it's an example for the SMS functionality, not even for flutter_whatsnew. 

```
example/README.md

flutter_sms_example #

Demonstrates how to use the flutter_sms plugin.

Getting Started #

For help getting started with Flutter, view our online documentation.
```

**Comment by AppleEducate** [comment]
Sorry, didn't catch that, This is one of my earlier plugins, ill update it

**Comment by AppleEducate** [comment]
Please check with the latest version `0.1.0`

**Comment by sjmcdowall** [comment]
Righto -- I'll give it a try tomorrow and report back ...

**Comment by AppleEducate** [comment]
Perfect!

Rody Davis Jr.
Full Stack Mobile Developer
Github | Website | Appstore | LinkedIn
Twitter | Facebook | YouTube
