### ISSUE TITLE
Pod error when using flutter_whatsnew

### ISSUE THREAD

**Issue by sjmcdowall** [AppleEducate/plugins#12]
With the beta channel of Flutter -- and using the latest flutter_whatsnew (0.0.7+2) I am getting the following error.  

Do you really need get_version in SWIFT?  To get the version in my program I am using PackageInfo directly with the following code:

```
      final PackageInfo info = await PackageInfo.fromPlatform();

      _versionName = info.version;
      _versionBuild = info.buildNumber;

```

And needless to say, no such errors as this:

    [!] Unable to determine Swift version for the following pods:

    - `get_version` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the
    targets that integrate this pod.

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer/xcode/target_validator.rb:115:in `verify_swift_pods_swift_version'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:459:in `validate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:138:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command/install.rb:48:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'
```

**Comment by AppleEducate** [comment]
No, i don't, for the original use case, I did, but not anymore. I'll update it and report back

**Comment by AppleEducate** [comment]
Please check with the latest version `0.1.0`
