### ISSUE TITLE
Sms read 

### ISSUE THREAD

**Issue by itsatifsiddiqui** [AppleEducate/plugins#14]
Please add in the feature to change the isread status to true upon sone action on the message.

**Comment by AppleEducate** [comment]
I am open to pull requests if you want to implement it quickly

**Comment by itsatifsiddiqui** [comment]
No, i don't want to. It would be appreciated, if you implement ...

**Comment by AppleEducate** [comment]
I'm closing this for now as there could be privacy issues on ios

**Comment by NTMS2017** [comment]
I have a MacBook Pro, how can I help? But I don't know about Xcode coding. I can help if you can help me to run the issues on Mac so your plugin it can work both android and iOS, thanks

**Comment by AppleEducate** [comment]
The issue is not the plug-in but Apple. There is no API Apple provides to allow reading of SMS.

**Comment by NTMS2017** [comment]
I see, can I read sms on Android or its same as Apple?

**Comment by AppleEducate** [comment]
Google is also cutting down on that and rejecting apps that do.

**Comment by NTMS2017** [comment]
Thanks
