### ISSUE TITLE
Send SMS within Flutter app instead of launching external app

### ISSUE THREAD

**Issue by faustinoribeiro** [AppleEducate/plugins#18]
Unless I am doing something very wrong, sending a SMS message using flutter_sms currently opens an external app.

I tried the 'sms' package (now unmaintained and with Android only support) and it allows to send an SMS from within a flutter app (permission from the user is required though). Would it be possible to add that functionality (even if it is only supported in Android)?

I have very basic native Android coding experience and none with iOS, but I wouldn't mind looking into implementing that functionality if I know it doesn't require extensive knowledge of the OS.

**Comment by AppleEducate** [comment]
It was possible until recently:

https://www.xda-developers.com/google-play-developer-policy-call-log-sms/

**Comment by faustinoribeiro** [comment]
I see, it makes sense. Thanks.

**Comment by AppleEducate** [comment]
No problem!
