### ISSUE TITLE
#import <flutter_sms/FlutterSmsPlugin.h> 

### ISSUE THREAD

**Issue by r3hmaanMalik** [AppleEducate/plugins#23]
#import <flutter_sms/FlutterSmsPlugin.h> is have not found when I try to archive on Xcode for submitting on apple store, everything working good while I test on the emulator or even my own real devices.

Thanks in advace.

**Comment by esfomeado** [comment]
How did you solve this problem?

Thanks

**Comment by esfomeado** [comment]
`flutter clean` did the trick.
