### ISSUE TITLE
responsive_scaffold: how to use nullItems?

### ISSUE THREAD

**Issue by divan** [AppleEducate/plugins#31]
Hi, thank you for the fantastic plugins. I'm using responsive_scaffold, and noticed that 'nullItems` is back a couple of days ago. I can't figure out how to use it, though (`emptyItems` works like a charm).

Any examples on how to tell ResponsiveScaffold.builder that data is null and display nice progress?

Thanks in advance!

**Comment by AppleEducate** [comment]
So if the items passed from the builder or children are null it will show that widget. I updated the example. I use it for a circular progress indicator. On the example if you replace the itemCount with null it will show

**Comment by divan** [comment]
Ah, it's `itemCount` should be null. Thanks, it works now, it's just name `nullItems` implies that `items` should be null, not `itemsCount` (but with a builder approach, there is no "direct" passing of items, so that's where things get confusing).
Thanks for help!

**Comment by AppleEducate** [comment]
Absolutely! I also did it this ways as I use slivers and want to intercept on null and empty instead of changing the whole widget. But you are welcome!
