### ISSUE TITLE
AudioUnitMIDISynth.swift

### ISSUE THREAD

**Issue by genedelisa** [AppleEducate/plugins#37]
This is code that I wrote without the credit. Thanks.

**Comment by AppleEducate** [comment]
Are you the author? If so I ported this from a native app I have had for a couple years and couldn’t find the original source.

What would you like me to link to and put in the code? Feel free to do a PR and or just let me know

**Comment by AppleEducate** [comment]
I really appreciate the work, I also have some questions about improvement.

**Comment by genedelisa** [comment]
It’s a copy of a previous version of this:

https://github.com/genedelisa/MIDISynth/blob/master/MIDISynth/AudioUnitMIDISynth.swift <https://github.com/genedelisa/MIDISynth/blob/master/MIDISynth/AudioUnitMIDISynth.swift>


Note the header and documentation comments are excised.


I publish my blog (http://rockhoppertech.com/blog <http://rockhoppertech.com/blog>) and these examples because Apple documentation sucks for audio/midi. Anyone who tries has to sweat blood to make it work. This is my attempt to help. I don’t get any money for the hours I spent. Only a low visibility ack.

For example this guy
https://github.com/spoonik/siner/blob/master/Commons/AudioUnitMIDISynth.swift <https://github.com/spoonik/siner/blob/master/Commons/AudioUnitMIDISynth.swift>

He uses the file, but intact.

**Comment by AppleEducate** [comment]
Do you have a paypal? I would like to send a couple bucks your way as a thank you. 

Also if you curious on the AppStore and Google Play the app “The Pitch Pipe” actually uses this for the midi.

It was a pain in the butt to right the midi plugin for android. They also have very poor documentation.

**Comment by genedelisa** [comment]
The project’s home page has a “buy my kitty some treats” button :)

https://github.com/genedelisa/MIDISynth

I updated that project not too long ago, so it’s current.

Send me your questions on what you need to do; I can probably add them.

In 2009 I looked at Android MIDI/sound and iOS. I’d been a Java developer since 1996.
I went with iOS at that time. Android was a mess in this area. Not entirely their fault due to so many manufacturers.
Latency was an issue. I don’t know about now.

Have fun today

**Comment by AppleEducate** [comment]
Just sent some kitty food haha!

And Here is my java implementation with no latency: https://github.com/AppleEducate/MidiDriver-Android-SF2

I have the project called flutter_piano and am looking to step through a midi track as they play notes. Any idea on how to do that with he midi spec

**Comment by AppleEducate** [comment]
I updated the file and will be released soon: https://github.com/AppleEducate/plugins/blob/master/packages/flutter_midi/ios/Classes/AudioUnitMIDISynth.swift
