### ISSUE TITLE
Can't send SMS on android

### ISSUE THREAD

**Issue by nitneuq33000** [AppleEducate/plugins#4]
Hello, I tried the plugin with the example. when I launch for the first time I have a pop up permission that I accept, but after I'm redirected to " information of application" , where I can select SMS in "authorization", but even with all this acceptation all my message go in the draft  and the native SMS app is open. I use a number with this format "06XXXXXXXX". I need only the simplest SMS pacakge, where I accept permissions and I can send sms without open the native SMS APP. thank you

**Comment by nitneuq33000** [comment]
It seems that the phone output format isn't correct, I have enter [06XXXXXXXX] and in output  avec have [06XXXXXXXX] instead of 06XXXXXXXX. I use  List<String> recipents = ["0123456789"];

**Comment by nitneuq33000** [comment]
here is my test code:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                              
`import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_sms/flutter_sms.dart';
void main() => runApp(SimpleSmsExampleApp());

class SimpleSmsExampleApp extends StatefulWidget {
  @override
  _SimpleSmsExampleAppState createState() => _SimpleSmsExampleAppState();
}

class _SimpleSmsExampleAppState extends State<SimpleSmsExampleApp> {

  void _sendSMS(String message, List<String> recipents) async {
    String _result = await FlutterSms
        .sendSMS(message: message, recipients: recipents)
        .catchError((onError) {
      print(onError);
    });
    print(_result);
  }

  String message = "This is a test message!";
  List<String> recipents = ["+33XXXXXXXXX","XXXXXXXXXX"];

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Simple sms example app'),
        ),
        body: Builder(
          builder: (BuildContext context) {
            return Column(
                children: <Widget>[

                  new Text("$recipents"),


                  new RaisedButton(
                    onPressed: () {
                      _sendSMS(message, recipents);
                    },
                    child: Text('Send SMS'),

                  )
                ]
            );
          },
        ),
      ),
    );
  }
}`                                                                                                                                                                                                                       
                                                                                                                                                                         
![screenshot_20181231-105955](https://user-images.githubusercontent.com/38652337/50558102-7158be80-0ceb-11e9-8990-3089a47a41dc.png)
![screenshot_20181231-110007](https://user-images.githubusercontent.com/38652337/50558107-7b7abd00-0ceb-11e9-987d-68403a87633a.png)
![screenshot_20181231-110016](https://user-images.githubusercontent.com/38652337/50558112-82a1cb00-0ceb-11e9-8a26-a3bfc43450ff.png)
![screenshot_20181231-110023](https://user-images.githubusercontent.com/38652337/50558116-8df4f680-0ceb-11e9-8288-27db8017dd25.png)
![screenshot_20181231-110028](https://user-images.githubusercontent.com/38652337/50558119-94836e00-0ceb-11e9-9c2e-3b044e0018dc.png)
                                                                                                                                                                        
  Currently tested on Android, I don't know If there is the same issue in iOS ?

**Comment by AppleEducate** [comment]
What would that error say in english?

**Comment by AppleEducate** [comment]
I updated the plugin to use the latest android API for sending messages.

**Comment by AppleEducate** [comment]
Please test with the latest version

**Comment by AppleEducate** [comment]
The latest version of the plugin no longer needs the read or send SMS permission

**Comment by AppleEducate** [comment]
This is working on the latest version of Android that I tested. Android P

**Comment by nitneuq33** [comment]
thank you for the update ! And for the permissions :) sI tried the 0.0.5 versio but I have this error : 
C:\Users\utilisateur\.gradle\caches\transforms-1\files-1.1\appcompat-1.0.0-beta01.aar\231e57cb7947525b16842900129342a0\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.
    
C:\Users\utilisateur\AndroidStudioProjects\test_sms_android\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.
    
C:\Users\utilisateur\.gradle\caches\transforms-1\files-1.1\appcompat-1.0.0-beta01.aar\231e57cb7947525b16842900129342a0\res\values\values.xml:1304:5-69: AAPT: error: resource android:attr/fontVariationSettings not found.
    
C:\Users\utilisateur\.gradle\caches\transforms-1\files-1.1\appcompat-1.0.0-beta01.aar\231e57cb7947525b16842900129342a0\res\values\values.xml:1304:5-69: AAPT: error: resource android:attr/ttcIndex not found.

I don't know what that means. 

I follow the request : up the minsdk to 18 or add <uses-sdk  tools:overrideLibrary="com.appleeducate.fluttersms"/> to the manifest but I have same issue

Currently I use minsdk 16. 

Other people with same observation ? 

thank you

**Comment by AppleEducate** [comment]
I’m pretty sure with Android X the min SDK needs to be 18, and the compile SDK needs to be 28!

Rody Davis Jr.
Full Stack Mobile Developer
Github | Website | Appstore | LinkedIn
Twitter | Facebook | YouTube

**Comment by AppleEducate** [comment]
please test with the latest version

**Comment by AppleEducate** [comment]
Fixed with Version `0.1.0`
