### ISSUE TITLE
[feature request] Standalone floating input

### ISSUE THREAD

**Issue by sajphon** [AppleEducate/plugins#43]
It would be cool if you could create also Floating input. Without integration with lists, for use as searchbar for maps for example.

**Comment by AppleEducate** [comment]
did you check the floating_search_bar plugin?
https://github.com/AppleEducate/plugins/tree/master/packages/floating_search_bar

You can use the sliver that is provided to do just this! 

For usage check out this example:
https://github.com/AppleEducate/gmail_clone

**Comment by AppleEducate** [comment]
Closing as it can be done with the current package
