### ISSUE TITLE
Not able to use app_review plugin

### ISSUE THREAD

**Issue by YAPPDEF** [AppleEducate/plugins#5]
Steps to reproduce:
1. create flutter project (with Objective C)
2. add app_review plugin in pubspeck.yaml
3. start app (simulator)

**Error**:
```
Xcode's output:
↳
=== BUILD TARGET shared_preferences OF PROJECT Pods WITH CONFIGURATION Debug ===
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.
```
> I needed to add SWIFT_VERSION (4.2) in Build Settings for my Flutter project (Objective C)

But when I fixed issue one, now this **error**:
```
** BUILD FAILED **
Xcode's output:
↳
=== BUILD TARGET package_info OF PROJECT Pods WITH CONFIGURATION Debug ===
/Users/xx/flutter/.pub-cache/hosted/pub.dartlang.org/app_review-0.0.9/ios/Classes/AppReviewPlugin.m:2:9: fatal error: 'app_review/app_review-Swift.h' file not found
#import <app_review/app_review-Swift.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by Matcho0** [comment]
You can add ‘use_framework!’ to the podfile of your flutter app to get past the above Swift error

**Comment by AppleEducate** [comment]
This requires swift for this plugin. Use @Matcho0 answer for compatibity

**Comment by Toolenaar** [comment]
@Matcho0  answer did not work for me. What worked for me was to add ‘use_frameworks!’. And then add a swift file to the iOS project using Xcode and accepting the create Bridging-Header option. This converted the project to support swift
