### ISSUE TITLE
Is there any chance to get flutter_midi running on Xcode Simulator?

### ISSUE THREAD

**Issue by thomasschwarzott** [AppleEducate/plugins#6]
Hello @AppleEducate! I'm just developing my first prototypical app with Flutter and I wanted to include music playback using MIDI notes. I stumbled upon your MIDI package and tried it out using your given example code.

Unfortunately, I am developing solely using the Xcode Simulator and I get the following error when trying to play back a MIDI note: 
`Could Not Load Midi on this Device. (Cannot run on simulator), have you included the sound font?`

I did include `sound_font.SF2` in my lib folder and registered it in my `pubspec.yaml`, however this shouldn't even be the problem as far as I can read.

I took a look into the package's `flutter_midi.dart` and found your hint that you're aware of the thing not working in Simulator.

`class FlutterMidi {`
`    static const MethodChannel _channel = MethodChannel('flutter_midi');`
` /// [...]`
`/// This does not work in the simulator.`

Is this something we simply can't get around until circumstances of Flutter/xCode/Dart change? Or is there a solution in sight, which just has to be developed yet?

Cheers,
Thomas

**Comment by AppleEducate** [comment]
I have looked into it and I ported the engine from my native android and iOS apps. At the time when I built it I did not see a way to load the midi engine on the simulator, not exactly sure why. I am definitely open to PRs. Eventually I was to bring the same sound font file (.sf2) to android too but right now they’re is no shared android and iOS midi engine. 

Plus I also have this weird issue on android with distorted playback even though it doesn’t happen on the example.

**Comment by AppleEducate** [comment]
It will definitely not work on the simulator after doing more research. It is how AVFoundation works in swift.

**Comment by ekomisarenko** [comment]
@AppleEducate with Catalina 10.15 and Xcode 11 you should be ok removing the conditional compilation from SwiftFlutterMidiPlugin.swift. I have tried with the latest Xcode simulator Version 11.0 (SimulatorApp-912.1 SimulatorKit-570.3 CoreSimulator-681.2) and the midi file seems to be playing fine on iOS simulator now. Note that I also had to set CFBundleVersion inside the /flutter_midi/example/ios/Runner/Info.plist file to a static string "1.0" or otherwise `flutter run` was failing on macOS.

**Comment by AppleEducate** [comment]
Absolutely ! Thats really cool that it works in the simulator now!
